### ISSUE TITLE
Enhancement request. Is ti possible to add a description column to the props table and a search? 

### ISSUE THREAD

**Issue by Dragod** [mattrothenberg/vue-elucidate#3]
Hi, I was looking for a vue automatic documentation, and this vue-elucidate is really what I need, thank you for doing this. But, I found 2 "issue" witch is the need at least on my project to have a description column on the props table also a search would be nice for component with lots of props. Since I don't know if there is a place where to ask for a possible request I did wrote it here, forgive me if the wrong place. Thank you.

**Comment by mattrothenberg** [comment]
Hi Fabio, this sounds like a great opportunity for you to submit a PR with the desired functionality.

Let me know if you need help getting started.
________________________________
